config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :books
  root "books#index"
  resources :users, except: [:index, :destroy]
  get "/sessions" => "sessions#destroy"
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :author, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, uniqueness: true
  has_many :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :authorize!
  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end
  def authorize!
    unless current_user
      redirect_to new_user_path
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :find_book, only: [:show, :destroy, :update, :edit]
  before_action :authorize!, except: [:show, :index]

  def index
    @books = Book.all
    # How to render up to the front end
    # render json: @books
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to books_path
    else
      redirect_to new_book_path
    end
  end

  def show
    @book
  end

  def destroy
    @book.delete
    redirect_to books_path
  end

  def edit
    @book
  end

  def update
    @book.update(book_params)
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :author, :description, :url)
  end

  def find_book
    @book = Book.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
  @current_session = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if @current_session
      session[:user_id] = @current_session.id
      redirect_to books_path
    else
      redirect_to new_session_path
    end
  end
  def destroy
    reset_session
    redirect_to new_session_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to books_path
    else
      redirect_to new_user_path
    end
  end
  def show
    @user = current_user
  end
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :url %>
  <%= f.text_field :url %>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <br>
  <%= f.submit %>

<% end %>

app/views/books/edit.html.erb
<h1>Edit your book</h1>
<%= render "form", book: @book %>

app/views/books/index.html.erb
<h1>Book List</h1>
<%= link_to "New Book", new_book_path %>
<br>
<br>

<% @books.each do |book|%>
  <%= book.title %>
  <%= book.author %>
  <%= link_to "Show", book %>
  <% if current_user&.id == book.user_id %>
  <%= link_to "Edit", edit_book_path(book) %>
  <%= link_to "Destroy", book, method: :delete %>
  <% end %>
  <br>
<% end %>

app/views/books/new.html.erb
<h1>Create a new Book</h1>
<%= render "form" %>
<%= link_to "Back", books_path %>

app/views/books/show.html.erb
<%= @book.title %>
<%= @book.author %>
<%= @book.description %>
<%= @book.url %>
<br>
<%= link_to "edit", edit_book_path(@book) %>
<%= link_to "Back", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wtfbbq</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to "logout", sessions_path %>
      <%= link_to "profile", user_path(current_user) %>
    <% else %>
      <%= link_to "login", new_session_path %>
      <%= link_to "create new user", new_user_path %>
      <% end %>
    <% link_to "home", books_path %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>User Profile</h1>
<% @user.books.each do |book| %>
<% book.title %>
<br>
<% end %>